### ISSUE TITLE
Shoe Repair shop - 30 Merchiston Avenue

### ISSUE THREAD

**Issue by ericgrosso** [osm-scotland/mappingedinburgh-issues#16]
https://www.openstreetmap.org/node/4930663254

According to this article (https://www.edinburghnews.scotsman.com/news/a-window-into-the-past-polwarth-shop-display-unchanged-in-over-30-years-1-4735711), this is maybe closed now.

A survey needs to be done.

**Comment by chrisfleming** [comment]
Should be passing by tomorrow....

**Comment by chrisfleming** [comment]
Keep forgetting to check....

**Comment by chrisfleming** [comment]
Sign indicates closed. Also looks like all stock in Tom Brown's has been removed, so will mark this as closed as well.
![mvimg_20181211_093839 1](https://user-images.githubusercontent.com/230932/50577095-c265d100-0e17-11e9-85dc-321099127ab9.jpg)
