### ISSUE TITLE
Bike Hire Stations.

### ISSUE THREAD

**Issue by chrisfleming** [osm-scotland/mappingedinburgh-issues#25]
Need to confirm the locations and add new bike hire stations. List is:

- [x]  Broughton Road
- [x] Brunswick Place
- [x] Lauriston Place
- [x] St Andrew Square
- [x] 1, Dean Bank Lane
- [x] Westbank Street
- [x] Regent Road
- [x] Kings Buildings Bus Stop and turning circle
- [x] James Dewar Road
- [x] Entrance to Sanderson Building
- [x] James Hutton Road
- [x] Waverley Station Concourse
- [x] Entrance to Scottish Government Office
- [x] 116 Fountainbridge
- [x] Bristo Square, Potter Row
- [x] Charlotte Square
- [x] Dalkeith Road, Edinburgh EH16 5BB
- [x] T05
- [x] Waverley Court, East Market Street
- [x] High Street
- [x] Waverley Bridge

Suggestion is to use: network=tfe_cycle_hire 

Opening on the 17th September.

**Comment by chrisfleming** [comment]
Locations are published under OGL and here: http://gbfs.urbansharing.com/edinburghcyclehire/station_information.json

**Comment by donaldrnoble** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental Is relavent 

I’ve got locations and capacity for 3 of 4 at KB will get the last tomorrow. 

Are we adding these to a relation? Or is that overkill?

**Comment by chrisfleming** [comment]
My feeling is that a relation is overkill - should be possible to find them all by operator.

Donald, can you tick off the stations as they are added above?

Also  for anyone having trouble viewing the json, this should help: https://jsoneditoronline.org/?url=http%3A%2F%2Fgbfs.urbansharing.com%2Fedinburghcyclehire%2Fstation_information.json

**Comment by donaldrnoble** [comment]
I didn’t realise the json had all the details, thought you’d just found a list of names. Should this just be imported and we can check them manually and tick off here?

**Comment by boothym** [comment]
> My feeling is that a relation is overkill - should be possible to find them all by operator.

Don't see any harm in having them all together in a relation?

**Comment by chrisfleming** [comment]
> 
> 
> > My feeling is that a relation is overkill - should be possible to find them all by operator.
> 
> Don't see any harm in having them all together in a relation?

It not so much that there is any harm in having them together in a relation, I just don't see it as adding any value.  I notice that wangi has added them all as network=edinburgh-city-bikes

and we can find them all using the network: network=edinburgh-city-bikes eg: http://overpass-turbo.eu/s/BUV

In addition because of this, the relation is an extra thing that requires maintenance, so when new bike stations are added, the mapper won't necessarily know to add them into the relation. 

Relations are useful where the relation provides either an extra layer, such as routes where a bunch of existing ways make up a route relation. Or where the relation has specific meaning such as multipolygons or turn restrictions, or even at a push the case for bridge/tunnel relations where a bunch of disperate things are part of the bridge. 

(as allways in OSM, feel free to add a relation, I just wanted to explain why I don't see any value)

**Comment by donaldrnoble** [comment]
The locations of the 4 at KB look accurate. Not sure if we just close this issue now?

**Comment by chrisfleming** [comment]
Agree, Closing.

**Comment by donaldrnoble** [comment]
Reopening this, as I see there are also designated "dockless" sites where the bikes can be dropped off, although these are just marked with an area of logo on the pavement .

- [x] I saw one at Shrubhill Sainsburys, 
- [x] https://twitter.com/cyclehire_edi/status/1050014734551052288 Comley Bank Waitrose
- [x] https://twitter.com/EdUniTransport/status/1047855124226498560 Reigo St Tollcross

**Comment by chrisfleming** [comment]
Added the ones above - also Bruntsfield and Ocean Terminal.

**Comment by chrisfleming** [comment]
Closing for now!
