### ISSUE TITLE
Leith Depot Closing

### ISSUE THREAD

**Issue by chrisfleming** [osm-scotland/mappingedinburgh-issues#39]
https://www.openstreetmap.org/note/1940097#map=19/55.96825/-3.17389&layers=N - latest is 31st October.

**Comment by chrisfleming** [comment]
Looks to still be open and listing events until the end of the year.

**Comment by donaldrnoble** [comment]
Presume this will stay open now as the development appeal has been thrown out https://www.edinburghlive.co.uk/news/edinburgh-news/leith-walk-saved-campaigners-rejoice-17451333

**Comment by chrisfleming** [comment]
Think so going to close this one out.
