### ISSUE TITLE
Tidy up old Hermitage Golf Course

### ISSUE THREAD

**Issue by chrisfleming** [osm-scotland/mappingedinburgh-issues#5]
Several notes:
https://www.openstreetmap.org/note/1450547
https://www.openstreetmap.org/note/1450542
https://www.openstreetmap.org/note/1450538

**Comment by chrisfleming** [comment]
Cycled past a few weeks ago, looks like pretty much all traces of the Golf course have gone. Service Road entrance still has a gate, but looked locked and definitly nothing more than a track. 

Also no sign of any holes or features so these can all be removed.

**Comment by ericgrosso** [comment]
Walked there the other day. I confirm that there is no more activity.

**Comment by ericgrosso** [comment]
Closed the notes as all of them have been resolved.
Removed all the features of the golf: https://www.openstreetmap.org/changeset/62117202
